### PR TITLE
fix: #203 added scrollbar in the table for small screen sizes

### PR DESCRIPTION
**Pull request by aashimawadhwa**
### What
-  added scrollbar in the table to make it responsive for smaller screen sizes

### Screenshot

Screenshot 2023-02-08 at 2 45 40 AM (2)

### Fixes bug(s)
-  #203

### CODE REVIEW

**Comment by aashimawadhwa** [comment]
@nobeeakon @alexgarel @diivi

**Review by nobeeakon — APPROVED** [review]
nice!!

**Comment by alexgarel** [comment]
@aashimawadhwa we may have the same problem on the Material table displaying properties for an issue.
* we would like it larger in the browser
* but shrinking on small devices

**Comment by alexgarel** [comment]
And thanks a lot for this first PR, small but accurate and very useful :smile:

**Pull request merged**
